import { useEffect, useState, type FormEvent } from "react";
type Step="profile"|"agreement"|"identity"|"review";
type State={status:string;reasonCode?:string|null;draft:any;identity:any;agreement:any;configuration:{onboardingEnabled:boolean;automaticApproval:boolean;maximumFileSizeBytes:number}};
export function CreatorOnboarding({language,step,api,onNavigate,onActivated,onBack}:{language:"en"|"zh";step:Step;api:(path:string,options?:RequestInit)=>Promise<any>;onNavigate:(step:Step|"status")=>void;onActivated:(user:any)=>void;onBack:()=>void}){
 const zh=language==="zh",[state,setState]=useState<State|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const [form,setForm]=useState({creatorHandle:"",displayName:"",bio:"",category:"Talk",primaryLanguage:language,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"America/Chicago",contentTags:""});
 const [signerName,setSignerName]=useState(""),[ageConfirmed,setAgeConfirmed]=useState(false),[agreementConfirmed,setAgreementConfirmed]=useState(false),[documentType,setDocumentType]=useState("passport"),[file,setFile]=useState<File|null>(null),[uploadProgress,setUploadProgress]=useState(0);
 const load=async()=>{const value=await api("/api/creator/onboarding");setState(value);if(value.draft){setForm({creatorHandle:value.draft.creator_handle??"",displayName:value.draft.display_name??"",bio:value.draft.bio??"",category:value.draft.category??"Talk",primaryLanguage:value.draft.primary_language??language,timezone:value.draft.timezone??"America/Chicago",contentTags:(value.draft.content_tags??[]).join(", ")});setSignerName(value.draft.display_name??"");}};
 useEffect(()=>{void load().catch(()=>setNotice(zh?"无法加载主播申请。":"Creator onboarding could not be loaded."));},[]);
 const run=async(task:()=>Promise<void>)=>{setBusy(true);setNotice("");try{await task();}catch{setNotice(zh?"无法完成此步骤。请检查信息后重试。":"This step could not be completed. Check the information and try again.");}finally{setBusy(false);}};
 if(!state)return <section className="creator-onboarding workspace" aria-busy="true"><p>{notice||(zh?"正在加载…":"Loading creator onboarding…")}</p></section>;
 if(state.status==="AUDIENCE")return <section className="creator-onboarding workspace onboarding-intro"><button className="secondary" onClick={onBack}>{zh?"返回发现":"Back to discovery"}</button><p className="eyebrow">{zh?"成为主播":"BECOME A CREATOR"}</p><h2>{zh?"创建主播账户":"Create your creator account"}</h2><p>{zh?"设置私密草稿资料、接受协议并安全上传身份证件。浏览此页面不会创建直播间。":"Create a private draft profile, accept the agreement, and securely upload an identity document. Viewing this page never creates a room."}</p><button disabled={busy||!state.configuration.onboardingEnabled} onClick={()=>void run(async()=>{await api("/api/creator/onboarding/start",{method:"POST",body:"{}"});await load();onNavigate("profile");})}>{zh?"开始":"Start creator onboarding"}</button></section>;
 if(["PENDING_REVIEW","REJECTED","SUSPENDED"].includes(state.status))return <section className="creator-onboarding workspace onboarding-status"><button className="secondary" onClick={onBack}>{zh?"返回发现":"Back to discovery"}</button><h2>{state.status.split("_").join(" ")}</h2><p>{state.reasonCode??(zh?"您的主播账户状态需要处理。":"Your creator account status needs attention.")}</p></section>;
 const steps:{id:Step;label:string}[]=[{id:"profile",label:zh?"资料":"Profile"},{id:"agreement",label:zh?"协议":"Agreement"},{id:"identity",label:zh?"证件":"Document"},{id:"review",label:zh?"确认":"Review"}];
 const allowed:Step=state.status==="ONBOARDING_PROFILE"?"profile":state.status==="ONBOARDING_AGREEMENT"?"agreement":state.status==="ONBOARDING_IDENTITY"?"identity":"review";const visible=steps.findIndex(x=>x.id===step)<=steps.findIndex(x=>x.id===allowed)?step:allowed;
 return <section className="creator-onboarding workspace"><div className="onboarding-heading"><div><p className="eyebrow">{zh?"主播入驻":"CREATOR ONBOARDING"}</p><h2>{zh?"设置主播账户":"Set up your creator account"}</h2></div><button className="secondary" onClick={onBack}>{zh?"稍后继续":"Resume later"}</button></div><ol className="onboarding-steps">{steps.map((x,i)=><li key={x.id} className={x.id===visible?"current":i<steps.findIndex(y=>y.id===allowed)?"complete":""}><span>{i+1}</span>{x.label}</li>)}</ol>
 {visible==="profile"?<form className="onboarding-form" onSubmit={(e:FormEvent)=>{e.preventDefault();void run(async()=>{await api("/api/creator/onboarding/profile",{method:"PATCH",body:JSON.stringify({...form,contentTags:form.contentTags.split(",").map(x=>x.trim()).filter(Boolean)})});await load();onNavigate("agreement");});}}><h3>{zh?"主播资料":"Creator profile"}</h3><label>{zh?"主播账号":"Creator handle"}<input required minLength={3} maxLength={30} pattern="[a-z0-9_-]+" value={form.creatorHandle} onChange={e=>setForm({...form,creatorHandle:e.target.value.toLowerCase()})}/></label><label>{zh?"显示名称":"Display name"}<input required minLength={2} maxLength={50} value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label>{zh?"简介":"Bio"}<textarea required minLength={20} maxLength={500} value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></label><div className="onboarding-form-row"><label>{zh?"类别":"Category"}<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>{zh?"主要语言":"Primary language"}<select value={form.primaryLanguage} onChange={e=>setForm({...form,primaryLanguage:e.target.value as "en"|"zh"})}><option value="en">English</option><option value="zh">中文</option></select></label></div><label>{zh?"时区":"Timezone (IANA)"}<input required value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></label><label>{zh?"内容标签":"Content tags"}<input value={form.contentTags} onChange={e=>setForm({...form,contentTags:e.target.value})}/></label><button disabled={busy}>{zh?"保存并继续":"Save and continue"}</button></form>:null}
 {visible==="agreement"?<form className="onboarding-form creator-agreement" onSubmit={e=>{e.preventDefault();void run(async()=>{await api("/api/creator/onboarding/agreement/accept",{method:"POST",body:JSON.stringify({agreementVersion:state.agreement.version,signerName,ageConfirmed,agreementConfirmed})});await load();onNavigate("identity");});}}><h3>{state.agreement?.title??"Holiwyn Creator Agreement"}</h3><p>{state.agreement?.content_text}</p><label>{zh?"签署姓名":"Signature name"}<input required minLength={2} value={signerName} onChange={e=>setSignerName(e.target.value)}/></label><label className="agreement-check"><input type="checkbox" required checked={ageConfirmed} onChange={e=>setAgeConfirmed(e.target.checked)}/>{zh?"我确认我已年满18岁。":"I confirm that I am at least 18 years old."}</label><label className="agreement-check"><input type="checkbox" required checked={agreementConfirmed} onChange={e=>setAgreementConfirmed(e.target.checked)}/>{zh?"我已阅读并同意 Holiwyn 主播协议和社区规则。":"I have read and agree to the Holiwyn Creator Agreement and Community Rules."}</label><button disabled={busy||!ageConfirmed||!agreementConfirmed}>{zh?"同意并继续":"Agree and continue"}</button></form>:null}
 {visible==="identity"?<div className="onboarding-panel identity-upload"><h3>{zh?"上传身份证件":"Upload identity document"}</h3><p>{zh?"证件仅用于私密账户审核，不会显示在公开资料中。目前不会执行自动身份验证；上传成功仅表示我们已收到文件。":"Your document is a private account-review record and is never public. We do not perform automated identity verification yet; successful upload only means the file was received."}</p><label>{zh?"证件类型":"Document type"}<select value={documentType} onChange={e=>setDocumentType(e.target.value)}><option value="passport">Passport</option><option value="national_id">National ID</option><option value="driver_license">Driver license</option></select></label><label>{zh?"PDF、JPEG 或 PNG，最大 8 MB":"PDF, JPEG, or PNG; maximum 8 MB"}<input type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>setFile(e.target.files?.[0]??null)}/></label>{busy?<progress max="100" value={uploadProgress}>{uploadProgress}%</progress>:null}<button disabled={busy||!file} onClick={()=>void run(async()=>{if(!file)return;setUploadProgress(25);const body=new FormData();body.append("document",file);setUploadProgress(55);await api(`/api/creator/onboarding/identity-document?documentType=${documentType}`,{method:"POST",body});setUploadProgress(100);await load();onNavigate("review");})}>{state.identity.status==="NEEDS_REUPLOAD"?(zh?"上传替换文件":"Upload replacement"):(zh?"上传并继续":"Upload and continue")}</button>{state.identity.status!=="NOT_UPLOADED"?<p role="status">{zh?`证件状态：${state.identity.status}`:`Document status: ${state.identity.status}`}</p>:null}</div>:null}
 {visible==="review"?<div className="onboarding-panel review-panel"><h3>{zh?"审核并激活":"Review and activate"}</h3><dl><div><dt>{zh?"主播":"Creator"}</dt><dd>@{state.draft?.creator_handle} · {state.draft?.display_name}</dd></div><div><dt>18+</dt><dd>{state.agreement?.age_confirmed?(zh?"已确认":"Confirmed"):(zh?"未确认":"Not confirmed")}</dd></div><div><dt>{zh?"协议":"Agreement"}</dt><dd>{state.agreement?.accepted?`${state.agreement.version} · ${state.agreement.signer_name}`:(zh?"未接受":"Not accepted")}</dd></div><div><dt>{zh?"身份证件":"Identity document"}</dt><dd>{state.identity.status}</dd></div></dl><p className="form-help">{zh?"收到证件不代表已验证身份。管理员可稍后审核；当前配置允许完成入驻后自动获得主播权限。":"Document receipt does not mean identity was verified. An administrator may review it later; current configuration allows creator access after onboarding is complete."}</p><button disabled={busy||!["UPLOADED","REVIEWED"].includes(state.identity.status)||!state.agreement?.age_confirmed||!state.agreement?.agreement_confirmed} onClick={()=>void run(async()=>{const result=await api("/api/creator/onboarding/activate",{method:"POST",body:"{}"});if(result.status==="ACTIVE"&&result.user)onActivated(result.user);else{await load();onNavigate("status");}})}>{zh?"激活主播账户":"Activate creator account"}</button><p className="form-help">{zh?"激活不会创建直播间、开始直播或请求摄像头/麦克风权限。":"Activation creates no room or broadcast and requests no camera or microphone permission."}</p></div>:null}{notice?<p className="account-notice" role="alert">{notice}</p>:null}</section>;
}
